import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { parse as parseYaml, stringify as stringifyYaml } from "yaml";
import {
  type AgentEndpointConfig,
  type AgentId,
  type ArrowConfig,
  type EndpointConfig,
  type ProviderId,
  type SwarmConfig,
  AGENT_ORDER,
  DEFAULT_NIM_BASE,
  DEFAULT_NIM_MODEL,
  DEFAULT_OPENAI_BASE,
  DEFAULT_OLLAMA_BASE,
  DEFAULT_SWARM,
} from "./types";
import {
  ARROW_HOME,
  CONFIG_PATH,
  ENV_PATH,
  SESSIONS_DIR,
  AGENTS_DIR,
  TEMPLATES_DIR,
  GOAL_PATH,
  SETTINGS_PATH,
  AGENTS_YAML_PATH,
  MEMORY_DIR,
} from "./paths";
import { bootstrapUserHome } from "../bootstrap/install-home";

export function ensureArrowHome(): void {
  // Create dirs only — content seeding is bootstrapUserHome()
  mkdirSync(ARROW_HOME, { recursive: true });
  mkdirSync(SESSIONS_DIR, { recursive: true });
  mkdirSync(AGENTS_DIR, { recursive: true });
  mkdirSync(TEMPLATES_DIR, { recursive: true });
  mkdirSync(MEMORY_DIR, { recursive: true });
}

export function loadDotEnv(): Record<string, string> {
  // Do NOT create home just to read env — only if .env already exists or home present
  const out: Record<string, string> = {};
  if (!existsSync(ENV_PATH)) return out;
  const text = readFileSync(ENV_PATH, "utf8");
  for (const line of text.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq <= 0) continue;
    const key = t.slice(0, eq).trim();
    let val = t.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    out[key] = val;
    if (!process.env[key]) process.env[key] = val;
  }
  return out;
}

export function saveEnv(vars: Record<string, string>): void {
  ensureArrowHome();
  const existing = existsSync(ENV_PATH)
    ? readFileSync(ENV_PATH, "utf8")
    : "# ArrowCode credentials — do not commit\n";
  const map = new Map<string, string>();
  for (const line of existing.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    const eq = t.indexOf("=");
    if (eq > 0) map.set(t.slice(0, eq).trim(), t.slice(eq + 1).trim());
  }
  for (const [k, v] of Object.entries(vars)) {
    if (v !== undefined && v !== null) map.set(k, v);
  }
  const lines = [
    "# ArrowCode — generated by setup / settings",
    "# Global: NVIDIA_API_KEY / OPENAI_API_KEY / ARROWCODE_*",
    "# Per-agent: ARROW_ORCH_API_KEY, ARROW_FE_MODEL, ARROW_BE_BASE_URL, ...",
    "",
  ];
  for (const [k, v] of map) lines.push(`${k}=${v}`);
  writeFileSync(ENV_PATH, lines.join("\n") + "\n", { mode: 0o600 });
  for (const [k, v] of Object.entries(vars)) process.env[k] = v;
}

export function isConfigured(): boolean {
  // process env first (no home required)
  const key =
    process.env.NVIDIA_API_KEY ||
    process.env.NIM_API_KEY ||
    process.env.OPENAI_API_KEY ||
    process.env.ANTHROPIC_API_KEY ||
    process.env.ARROWCODE_API_KEY;
  if (key) return true;
  if (process.env.ARROWCODE_PROVIDER === "ollama") return true;
  for (const p of ["ORCH", "FE", "BE", "QA"]) {
    if (process.env[`ARROW_${p}_API_KEY`]) return true;
  }
  // only then peek at user home files if they already exist
  loadDotEnv();
  if (existsSync(ENV_PATH)) {
    const again =
      process.env.NVIDIA_API_KEY ||
      process.env.OPENAI_API_KEY ||
      process.env.ARROWCODE_API_KEY;
    if (again) return true;
  }
  if (existsSync(CONFIG_PATH)) {
    try {
      const c = parseYaml(readFileSync(CONFIG_PATH, "utf8")) as Partial<ArrowConfig>;
      if (c.provider === "ollama" || c.apiKey) return true;
    } catch {
      /* */
    }
  }
  return false;
}

function providerDefaults(provider: ProviderId): {
  baseUrl: string;
  model: string;
  envKey: string;
} {
  switch (provider) {
    case "nim":
      return {
        baseUrl: DEFAULT_NIM_BASE,
        model: DEFAULT_NIM_MODEL,
        envKey: "NVIDIA_API_KEY",
      };
    case "openai":
      return {
        baseUrl: DEFAULT_OPENAI_BASE,
        model: "gpt-4.1",
        envKey: "OPENAI_API_KEY",
      };
    case "anthropic":
      return {
        baseUrl: "https://api.anthropic.com/v1",
        model: "claude-sonnet-4-20250514",
        envKey: "ANTHROPIC_API_KEY",
      };
    case "ollama":
      return {
        baseUrl: DEFAULT_OLLAMA_BASE,
        model: "qwen2.5-coder:14b",
        envKey: "OLLAMA_API_KEY",
      };
    default:
      return {
        baseUrl: DEFAULT_OPENAI_BASE,
        model: DEFAULT_NIM_MODEL,
        envKey: "ARROWCODE_API_KEY",
      };
  }
}

const AGENT_ENV_PREFIX: Record<AgentId, string> = {
  orchestrator: "ORCH",
  frontend: "FE",
  backend: "BE",
  tester: "QA",
};

/** Load agents.yaml if present. */
export function loadAgentsYaml(): Partial<Record<AgentId, AgentEndpointConfig>> {
  if (!existsSync(AGENTS_YAML_PATH)) return {};
  try {
    const raw = parseYaml(readFileSync(AGENTS_YAML_PATH, "utf8")) as Record<
      string,
      AgentEndpointConfig
    >;
    const out: Partial<Record<AgentId, AgentEndpointConfig>> = {};
    for (const id of AGENT_ORDER) {
      if (raw[id]) out[id] = raw[id];
      // also accept short keys
      const short = AGENT_META_SHORT[id];
      if (raw[short]) out[id] = { ...out[id], ...raw[short] };
    }
    return out;
  } catch {
    return {};
  }
}

const AGENT_META_SHORT: Record<AgentId, string> = {
  orchestrator: "orch",
  frontend: "fe",
  backend: "be",
  tester: "qa",
};

export function saveAgentsYaml(
  endpoints: Partial<Record<AgentId, AgentEndpointConfig>>,
): void {
  ensureArrowHome();
  // strip empty api keys from file — prefer env for secrets
  const safe: Record<string, AgentEndpointConfig> = {};
  for (const id of AGENT_ORDER) {
    const e = endpoints[id];
    if (!e) continue;
    const copy = { ...e };
    if (copy.apiKey) {
      // keep placeholder note only if user explicitly wants file storage
      // still allow saving; chmod note in README
    }
    safe[id] = copy;
  }
  writeFileSync(
    AGENTS_YAML_PATH,
    `# Per-agent API endpoints for ArrowCode\n` +
      `# Prefer env: ARROW_FE_API_KEY, ARROW_BE_MODEL, etc.\n` +
      stringifyYaml(safe),
    { mode: 0o600 },
  );
}

/** Resolve effective endpoint for a main agent (or worker root). */
export function resolveEndpoint(
  cfg: ArrowConfig,
  agentId: AgentId,
): EndpointConfig {
  const yaml = cfg.agentEndpoints?.[agentId] || {};
  const prefix = AGENT_ENV_PREFIX[agentId];
  const envProvider = process.env[`ARROW_${prefix}_PROVIDER`] as ProviderId | undefined;
  const envModel = process.env[`ARROW_${prefix}_MODEL`];
  const envKey = process.env[`ARROW_${prefix}_API_KEY`];
  const envBase = process.env[`ARROW_${prefix}_BASE_URL`];

  const provider = (yaml.provider ||
    envProvider ||
    cfg.provider) as ProviderId;
  const defs = providerDefaults(provider);

  return {
    provider,
    model:
      yaml.model ||
      envModel ||
      cfg.agentModels?.[agentId] ||
      cfg.model ||
      defs.model,
    apiKey:
      yaml.apiKey ||
      envKey ||
      cfg.apiKey ||
      (provider === "ollama" ? "ollama" : ""),
    baseUrl: yaml.baseUrl || envBase || cfg.baseUrl || defs.baseUrl,
    temperature: yaml.temperature ?? cfg.temperature,
    maxTokens: yaml.maxTokens ?? cfg.maxTokens,
  };
}

export function loadConfig(overrides: Partial<ArrowConfig> = {}): ArrowConfig {
  loadDotEnv();
  // Home is created by setup/install/bootstrap — not required to *read* global env config

  let file: Partial<ArrowConfig> = {};
  if (existsSync(CONFIG_PATH)) {
    try {
      file =
        (parseYaml(readFileSync(CONFIG_PATH, "utf8")) as Partial<ArrowConfig>) ||
        {};
    } catch {
      file = {};
    }
  }
  if (existsSync(SETTINGS_PATH)) {
    try {
      const s =
        (parseYaml(readFileSync(SETTINGS_PATH, "utf8")) as Partial<ArrowConfig>) ||
        {};
      file = { ...file, ...s };
    } catch {
      /* */
    }
  }

  const provider = (overrides.provider ||
    process.env.ARROWCODE_PROVIDER ||
    file.provider ||
    "nim") as ProviderId;
  const defs = providerDefaults(provider);

  const apiKey =
    overrides.apiKey ||
    process.env.ARROWCODE_API_KEY ||
    process.env.NVIDIA_API_KEY ||
    process.env.NIM_API_KEY ||
    process.env.OPENAI_API_KEY ||
    process.env.ANTHROPIC_API_KEY ||
    file.apiKey ||
    (provider === "ollama" ? "ollama" : "");

  const baseUrl =
    overrides.baseUrl ||
    process.env.ARROWCODE_BASE_URL ||
    file.baseUrl ||
    defs.baseUrl;

  const model =
    overrides.model ||
    process.env.ARROWCODE_MODEL ||
    file.model ||
    defs.model;

  const workspace =
    overrides.workspace ||
    process.env.ARROWCODE_WORKSPACE ||
    file.workspace ||
    process.cwd();

  const swarm: SwarmConfig = {
    ...DEFAULT_SWARM,
    ...(file.swarm || {}),
    ...(overrides.swarm || {}),
  };

  const agentEndpoints: Partial<Record<AgentId, AgentEndpointConfig>> = {
    ...loadAgentsYaml(),
    ...(file.agentEndpoints || {}),
    ...(overrides.agentEndpoints || {}),
  };

  return {
    provider,
    model,
    apiKey,
    baseUrl,
    temperature: overrides.temperature ?? file.temperature ?? 0.2,
    maxTokens: overrides.maxTokens ?? file.maxTokens ?? 8192,
    maxToolRounds: overrides.maxToolRounds ?? file.maxToolRounds ?? 28,
    maxExecuteCycles: overrides.maxExecuteCycles ?? file.maxExecuteCycles ?? 12,
    autoApprove:
      overrides.autoApprove ??
      (process.env.ARROWCODE_YOLO === "1" ||
      process.env.ARROWCODE_YOLO === "true"
        ? true
        : (file.autoApprove ?? false)),
    workspace,
    agentModels: overrides.agentModels || file.agentModels,
    agentsEnabled: overrides.agentsEnabled ||
      file.agentsEnabled || {
        orchestrator: true,
        frontend: true,
        backend: true,
        tester: true,
      },
    agentEndpoints,
    templateId: overrides.templateId ?? file.templateId,
    goal: overrides.goal ?? file.goal,
    systemExtra: overrides.systemExtra ?? file.systemExtra,
    swarm,
    contextBudgetChars:
      overrides.contextBudgetChars ?? file.contextBudgetChars ?? 120_000,
  };
}

export function saveConfig(cfg: Partial<ArrowConfig>): void {
  ensureArrowHome();
  let existing: Record<string, unknown> = {};
  if (existsSync(CONFIG_PATH)) {
    try {
      existing =
        (parseYaml(readFileSync(CONFIG_PATH, "utf8")) as Record<
          string,
          unknown
        >) || {};
    } catch {
      existing = {};
    }
  }
  writeFileSync(CONFIG_PATH, stringifyYaml({ ...existing, ...cfg }), "utf8");
}

export function saveSettings(cfg: Partial<ArrowConfig>): void {
  ensureArrowHome();
  const safe: Record<string, unknown> = {
    provider: cfg.provider,
    model: cfg.model,
    baseUrl: cfg.baseUrl,
    temperature: cfg.temperature,
    maxTokens: cfg.maxTokens,
    maxToolRounds: cfg.maxToolRounds,
    maxExecuteCycles: cfg.maxExecuteCycles,
    autoApprove: cfg.autoApprove,
    agentModels: cfg.agentModels,
    agentsEnabled: cfg.agentsEnabled,
    agentEndpoints: stripKeys(cfg.agentEndpoints),
    templateId: cfg.templateId,
    goal: cfg.goal,
    systemExtra: cfg.systemExtra,
    swarm: cfg.swarm,
    contextBudgetChars: cfg.contextBudgetChars,
  };
  writeFileSync(SETTINGS_PATH, stringifyYaml(safe), "utf8");
  saveConfig(safe as Partial<ArrowConfig>);
  if (cfg.agentEndpoints) {
    // persist full endpoints (including keys) only to agents.yaml with 0600
    saveAgentsYaml(cfg.agentEndpoints);
  }
}

function stripKeys(
  ep?: Partial<Record<AgentId, AgentEndpointConfig>>,
): Partial<Record<AgentId, AgentEndpointConfig>> | undefined {
  if (!ep) return undefined;
  const out: Partial<Record<AgentId, AgentEndpointConfig>> = {};
  for (const id of AGENT_ORDER) {
    if (!ep[id]) continue;
    const { apiKey: _k, ...rest } = ep[id]!;
    out[id] = rest;
  }
  return out;
}

export function resolveApiKeyEnvName(provider: ProviderId): string {
  return providerDefaults(provider).envKey;
}

export function loadGoalFile(): string {
  // Never create ~/.arrowcode just to read a missing goal
  if (!existsSync(GOAL_PATH)) return "";
  try {
    return readFileSync(GOAL_PATH, "utf8");
  } catch {
    return "";
  }
}

export function saveGoalFile(text: string): void {
  // Only write to user home if it already exists; else caller should use workspace session
  try {
    if (!existsSync(ARROW_HOME)) {
      // best-effort: skip global goal persist without install
      return;
    }
    // Home exists: write goal without recreating full tree if possible
    writeFileSync(GOAL_PATH, text, "utf8");
  } catch {
    /* non-fatal */
  }
}

export function writeExampleAgentsYaml(): void {
  bootstrapUserHome();
}
